<!DOCTYPE HTML>
<!--
	Miniport by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Vyesl</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="css/main.css" />
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie9.css" /><![endif]-->
	</head>
	<body>

		<!-- Nav -->
			<nav id="nav">
				<ul class="container">
					<li><a href="#top">Top</a></li>
					<li><a href="#school">School</a></li>
					<li><a href="#work">Work</a></li>
					<li><a href="#portfolio">Portfolio</a></li>
					<li><a href="#contact">Contact</a></li>
				</ul>
			</nav>

		<!-- Home -->
			<div class="wrapper style1 first">
				<article class="container" id="top">
					<div class="row">
						<div class="4u 12u(mobile)">
							<span class="image fit"><img src="http://i.imgur.com/75NoPUD.jpg" alt="" /></span>
						</div>
						<div class="8u 12u(mobile)">
							<header>
								<h1>Hi. I'm <strong>Đoàn Duy Thuỳ Vy</strong>.</h1>
							</header>
							<p>I'm glad about your visit on my resume - <a href="http://www.vyesl.us">http://www.vyesl.us</a>. Hope that you have had a good experience.</p>
							<a href="#school" class="button big scrolly">Check what I've learned</a>
						</div>
					</div>
				</article>
			</div>


			<!-- School -->
				<div class="wrapper style2">
					<article id="school">
						<header>
							<h2>Here's the place I've studied at</h2>
							<p>"Learning never exhausts the mind." - Leonardo da Vinci</p>
						</header>
						<div class="container">
							<div class="row">

									<section class="box style1">
										<span class="icon featured"><img src="images/huflit-logo.jpg" width="200"></span>
										<h3>UNIVERSITY OF FOREIGN LANGUAGES AND INFORMATION TECHNOLOGY (HUFLIT) </h3>
										<p style="text-align:left;"><br/>
<b>Bachelor of Arts, International  Relations</b> | 2007-2011  <br/></p>
<p style="text-align:left;">Majors:
<li style="text-align:left;">	Public Relations  </li>
	<li style="text-align:left;">	Marketing </li>
		<li style="text-align:left;">	English </li>
	</p>
<p style="text-align:left;">
INTERNATIONAL ENGLISH LANGUAGE TESTING SYSTEM (IELTS)  <br/>
Overall mark: 6.0  <br/>

		</p>
									</section>

							</div>
						</div>
						<footer>
							<p>Interesting?</p>
							<a href="#work" class="button big scrolly">Learn about what I do</a>
						</footer>
					</article>
				</div>


		<!-- Work -->
			<div class="wrapper style2">
				<article id="work">
					<header>
						<h2>Here's all line of work I've done.</h2>
						<p>"The best preparation for good work tomorrow is to do good work today." - Elbert Hubbard</p>
					</header>
					<div class="container">
						<div class="row">

								<section class="box style1">
									<span class="icon featured"><img src="images/me-corp.jpg" width="200"></span>
									<h3>MOBILE ENTERTAINMENT COMPANY, VIETNAM</h3>
									<p style="text-align:left;">Mecorp is one of the leading companies in the field of service-oriented development to provide digital content on mobile devices.<br/> <br/>
										Position: <b>Officer of Human Resource</b> | Full time | June 2014 - now </p>
										<li style="text-align:left;"> Work closely with accounting and finance departments to track and manage employee time (Timekeeper).</li>
										<li style="text-align:left;">	Support training department: make payment request for internal tuition, prepare statistic report & report to higher level on program quality.</li>
										<li style="text-align:left;">	Administer company recruitment’s fan page: find appropriate content, brainstorm for new idea.</li>
										<li style="text-align:left;">	Organize-Administrate "Meer Companion" program.</li>
										<li style="text-align:left;">	Monitor yearly leaves and working days.</li>
											<li style="text-align:left;">Welcome new employees.</li>
												<li style="text-align:left;">Monitor and conduct benefit policy for employee (family anniversary, death, other procedure policy...)</li>
													<li style="text-align:left;"> Consult health insurance policy annually</li>
														<li style="text-align:left;"> Wrap up & finish necessary steps for emloyee's departure.</li>
														<p style="text-align:left;">

															<br/>
     Position: <b>Officer of Internal Communication</b> | Full time | May – Sep 2013
		<li style="text-align:left;">	Administer company’s fanpage and website </li>
			<li style="text-align:left;">	Organize company events including sport and other entertainment contests for colleagues.  </li>
				<li style="text-align:left;">	Union Secretary.  </li>
</p>
								</section>


								<section class="box style1">
									<span class="icon featured fa-usd"></span>
									<h3>HUONG  MY CO. LTD – HO CHI MINH CITY, VIETNAM</h3>
									<p style="text-align:left;">Huong My is a trading company, importing a variety of products ranging from sports equipments to luxury cosmetics. The company is the exclusive distributor of “Givenchy” brand in Vietnam and owns a distribution channel of 5 stores in lucrative shopping centers namely Parkson, Paragon etc.<br/> <br/>
Position: <b>Administrative Officer</b> | Intern and Part-time | Jan - Sep 2011
<li style="text-align:left;">	Edit in-house magazines, case studies, speeches, leaflets and annual reports.</li>
	<li style="text-align:left;">	Take part in company’s organizing team for media events including press conferences, exhibitions.</li>
		<li style="text-align:left;">	Translate contracts and prepare documents. </li>

</p>
								</section>


								<section class="box style1">
									<span class="icon featured"><img src="images/HC.JPG" height="200"></span>
									<h3>HIGHLAND COFFEE – HCMC , VIETNAM</h3>
									<p style="text-align:left;">Highland Coffee is a well-known cafeteria chain with outlets nationwide.<br/> <br/>
Position: <b>Waitress</b> | Part time | 2010
								</section>

						</div>
					</div>
					<footer>
						<p>Looking for more?</p>
						<a href="#portfolio" class="button big scrolly">See some of my recent work</a>
					</footer>
				</article>
			</div>

		<!-- Portfolio -->
			<div class="wrapper style3">
				<article id="portfolio">
					<header>
						<h2>Here’s some activities I was in operation recently.</h2>
						<p>"There is only one corner of the universe you can be certain of improving, and that's your own self." ― Aldous Huxley</p>
					</header>
					<div class="container">
						<div class="row">
							<div class="4u 12u(mobile)">
								<article class="box style2">
									<!-- <a class="image featured" id="leanModal" href="#job1"><img src="images/thuy.jpg" alt="" /></a> -->
									<h3><a id="leanModal" href="#job1">“THUY’S DREAM” NATION-WIDE CAMPAIGN</a></h3>

								</article>
							</div>
							<div class="4u 12u(mobile)">
								<article class="box style2">
									<!--	<a id="leanModal" href="#job2" class="image featured"><img src="images/dioxin.jpg" alt="" /></a> -->
									<h3><a id="leanModal" href="#job2">SOCIAL PHOTO DISPLAY TO SUPPORT DIOXIN-POISONED VICTIMS </a></h3>

								</article>
							</div>
							<div class="4u 12u(mobile)">
								<article class="box style2">
								<!--		<a id="leanModal" href="#job3" class="image featured"><img src="images/huflit.jpg" alt="" /></a> -->
									<h3><a id="leanModal" href="#job3">UNIVERSITY CAMPING TRIP – “HUFLIT’S 36 HOURS of LOVE”</a></h3>

								</article>
							</div>
						</div>

						<div id="job1" class="article">
							<p>Active member participating in “Thuy’s Dream” program, which was initiated by a major national newspaper, to provide material and spiritual support to children with cancer.     </p>
						</div>

						<div id="job2" class="article">
							<p>Organizer of a social photo display to raise funds from local corporations for dioxin-poisoned victims in 2010. </p>
						</div>

						<div id="job3" class="article">
							<p>Key organizer of the University 2-day camping trip for more than a hundred students to a beach city 200km away from Ho Chi Minh City.</p>
						</div>

					</div>
					<footer>
						<p>Have a good impression?</p>
						<a href="#contact" class="button big scrolly">Get in touch with me</a>
					</footer>
				</article>
			</div>

		<!-- Contact -->
			<div class="wrapper style4">
				<article id="contact" class="container 75%">

					<div>
					<!--	<div class="row">
							<div class="12u">
								<form method="post" action="#">
									<div>
										<div class="row">
											<div class="6u 12u(mobile)">
												<input type="text" name="name" id="name" placeholder="Name" />
											</div>
											<div class="6u 12u(mobile)">
												<input type="text" name="email" id="email" placeholder="Email" />
											</div>
										</div>
										<div class="row">
											<div class="12u">
												<input type="text" name="subject" id="subject" placeholder="Subject" />
											</div>
										</div>
										<div class="row">
											<div class="12u">
												<textarea name="message" id="message" placeholder="Message"></textarea>
											</div>
										</div>
										<div class="row 200%">
											<div class="12u">
												<ul class="actions">
													<li><input type="submit" value="Send Message" /></li>
													<li><input type="reset" value="Clear Form" class="alt" /></li>
												</ul>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div> -->
						<div class="row">
							<div class="12u">

								<header>
									<h2>Have me make stuff for you.</h2>
									<p>"We are what we repeatedly do. Excellence then, is not an act, but a habit." – Aristotle</p>
								</header>
								<h3>Find me on ...</h3>
								<ul class="social">
									<li><a target="_blank" href="https://www.facebook.com/doanduy.vy" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
									<li><a href="https://vn.linkedin.com/pub/vy-doan/82/4a2/682" class="icon fa-linkedin"><span class="label">LinkedIn</span></a></li>
									<li><a href="skype:vy.esl?chat" class="icon fa-skype"><span class="label">Skype</span></a></li>
									<li><a href="mailto:doanduy.vy@gmail.com" class="icon fa-envelope"><span class="label">Skype</span></a></li>
									<li><a href="tel:+84949826170" class="icon fa-phone" alt="+84949826170"><span class="label">Phone</span></a></li>
									<!--
									<li><a href="#" class="icon fa-rss"><span>RSS</span></a></li>
									<li><a href="#" class="icon fa-instagram"><span>Instagram</span></a></li>
									<li><a href="#" class="icon fa-foursquare"><span>Foursquare</span></a></li>
									<li><a href="#" class="icon fa-skype"><span>Skype</span></a></li>
									<li><a href="#" class="icon fa-soundcloud"><span>Soundcloud</span></a></li>
									<li><a href="#" class="icon fa-youtube"><span>YouTube</span></a></li>
									<li><a href="#" class="icon fa-blogger"><span>Blogger</span></a></li>
									<li><a href="#" class="icon fa-flickr"><span>Flickr</span></a></li>
									<li><a href="#" class="icon fa-vimeo"><span>Vimeo</span></a></li>
									-->
								</ul>
								<hr />
							</div>
						</div>
					</div>
					<footer>
						<ul id="copyright">
							<li>&copy; All rights reserved.</li><li>Created by: <a href="https://tuannvm.com">Tuan Nguyen</a></li>
						</ul>
					</footer>
				</article>
			</div>

		<!-- Scripts -->
			<script src="js/jquery.min.js"></script>
			<script src="js/jquery.scrolly.min.js"></script>
			<script src="js/skel.min.js"></script>
			<script src="js/skel-viewport.min.js"></script>
			<script src="js/util.js"></script>
			<!--[if lte IE 8]><script src="js/ie/respond.min.js"></script><![endif]-->
			<script src="js/main.js"></script>
			<script type="text/javascript" src="js/jquery.leanModal.min.js"></script>
			<script src="js/dialog.js"></script>

	</body>
</html>
