<!DOCTYPE HTML>
<!--
	Miniport by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Vyesl</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="css/main.css" />
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie9.css" /><![endif]-->
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	</head>
	<body>

		<!-- Nav -->
			<nav id="nav">
				<ul class="container">
					<li><a href="#top">Top</a></li>
					<li><a href="#school">School</a></li>
					<li><a href="#work">Work</a></li>
					<li><a href="#portfolio">Portfolio</a></li>
					<li><a href="#interest">Interest</a></li>
					<li><a href="#contact">Contact</a></li>
				</ul>
			</nav>

		<!-- Home -->
			<div class="wrapper style1 first">
				<article class="container" id="top">
					<div class="row">
						<div class="4u 12u(mobile)">
							<span class="image fit"><img src="http://i.imgur.com/75NoPUD.jpg" alt="" /></span>
						</div>
						<div class="8u 12u(mobile)" style="font-size: 90%">
							<header>
								<h1>Hi. I'm <strong>Đoàn Duy Thuỳ Vy</strong>.</h1>
							</header>
							<p>As a HR executive with 3 year experience,  being responsible for organization development that generates the culture of the organization, I've learnt to live with stressful tasks, ambiguous guidelines, etc... . And thanks to those difficulties, I've been able to develop my skill assets, which make me a good planner and a "plan B-is-always-available" crew member. Moreover, I'm exceptionally calm during the emergency case, and that help me get through a handful of times when a lot of people were counting on HR team.</p>
<P>Keeping good connection with colleagues, in my opinion, is the crucial aspect of the person working in human-related fields.  Added to that, I'm considered as a reliable person, who always take full responsibility for assigned tasks and think twice before making any decision.</p>
							<a href="#school" class="button big scrolly">Check what I've learned</a>
						</div>
					</div>
				</article>
			</div>


			<!-- School -->
				<div class="wrapper style2">
					<article id="school">
						<header>
							<h2>Here's the place I've studied at</h2>
							<p>"Learning never exhausts the mind." - Leonardo da Vinci</p>
						</header>
						<div class="container">
							<div class="row">

									<section class="box style1">
										<span class="icon featured"><img src="images/huflit-logo.jpg" width="200"></span>
										<h3>UNIVERSITY OF FOREIGN LANGUAGES AND INFORMATION TECHNOLOGY (HUFLIT) </h3>
										<p style="text-align:left;"><br/>
<b>Bachelor of Arts, International  Relations</b> | 2007-2011  <br/></p>
<p style="text-align:left;">Majors:
<li style="text-align:left;">	Public Relations  </li>
	<li style="text-align:left;">	Marketing </li>
		<li style="text-align:left;">	English </li>
	</p>
<p style="text-align:left;">
INTERNATIONAL ENGLISH LANGUAGE TESTING SYSTEM (IELTS)  <br/>
Overall mark: 6.0  <br/>

		</p>
									</section>

							</div>
						</div>
						<footer>
							<p>Interesting?</p>
							<a href="#work" class="button big scrolly">Learn about what I do</a>
						</footer>
					</article>
				</div>


		<!-- Work -->
			<div class="wrapper style2">
				<article id="work">
					<header>
						<h2>Here's all line of work I've done.</h2>
						<p>"The best preparation for good work tomorrow is to do good work today." - Elbert Hubbard</p>
					</header>
					<div class="container">
						<div class="row">

								<section class="box style1">
									<span class="icon featured"><img src="images/me-corp.jpg" width="200"></span>
									<h3>MOBILE ENTERTAINMENT COMPANY, VIETNAM</h3>
									<p style="text-align:left;">Mecorp is one of the leading companies in the field of service-oriented development to provide digital content on mobile devices.<br/> <br/>
										Position: <b>Officer of Human Resource</b> | Full time | June 2014 - now </p>
										<li style="text-align:left;"> Work closely with accounting and finance departments to track and manage employee time (Timekeeper).</li>
										<li style="text-align:left;">	Support training department: make payment request for internal tuition, prepare statistic report & report to higher level on program quality.</li>
										<li style="text-align:left;">	Administer company recruitment’s fan page: find appropriate content, brainstorm for new idea.</li>
										<li style="text-align:left;">	Organize-Administrate "Meer Companion" program.</li>
										<li style="text-align:left;">	Monitor yearly leaves and working days.</li>
											<li style="text-align:left;">Welcome new employees.</li>
												<li style="text-align:left;">Monitor and conduct benefit policy for employee (family anniversary, death, other procedure policy...)</li>
													<li style="text-align:left;"> Consult health insurance policy annually</li>
														<li style="text-align:left;"> Wrap up & finish necessary steps for emloyee's departure.</li>
														<p style="text-align:left;">

															<br/>
     Position: <b>Officer of Internal Communication</b> | Full time | May – Sep 2013
		<li style="text-align:left;">	Administer company’s fanpage and website </li>
			<li style="text-align:left;">	Organize company events including sport and other entertainment contests for colleagues.  </li>
				<li style="text-align:left;">	Union Secretary.  </li>
</p>
								</section>

						</div>
					</div>
					<footer>
						<p>Looking for more?</p>
						<a href="#interest" class="button big scrolly">Check out my interests</a>
					</footer>
				</article>
			</div>

		<!-- Interest -->
				<div class="wrapper style2">
					<article id="interest">
						<header>
							<h2>Fields I want to work on</h2>
							<p>"Success is the result of perfection, hard work, learning from failure, loyalty, and persistence." - Colin Powell</p>
						</header>
						<div class="container">
							<div class="row">

									<section class="box style1">
										<h3 class="text-warning icon fa-facebook">ashion</h3>
										<h3 class="text-success icon fa-home"> Decoration</h3>
										<h3 class="text-info icon fa-suitcase"> Agent</h3>
									</section>

							</div>
						</div>
						<footer>
							<p>Impressed?</p>
							<a href="#portfolio" class="button big scrolly">See some of my recent work</a>
						</footer>
					</article>
				</div>

		<!-- Portfolio -->
			<div class="wrapper style3">
				<article id="portfolio">
					<header>
						<h2>Here’s some activities I was in operation recently.</h2>
						<p>"There is only one corner of the universe you can be certain of improving, and that's your own self." ― Aldous Huxley</p>
					</header>
					<div class="container">
						<div class="row">
							<div class="4u 12u(mobile)">
								<article class="box style2">
									<!-- <a class="image featured" id="leanModal" href="#job1"><img src="images/thuy.jpg" alt="" /></a> -->
									<h3><a id="leanModal" href="#">“THUY’S DREAM” NATION-WIDE CAMPAIGN</a></h3>

								</article>
							</div>
							<div class="4u 12u(mobile)">
								<article class="box style2">
									<!--	<a id="leanModal" href="#job2" class="image featured"><img src="images/dioxin.jpg" alt="" /></a> -->
									<h3><a id="leanModal" href="#">SOCIAL PHOTO DISPLAY TO SUPPORT DIOXIN-POISONED VICTIMS </a></h3>

								</article>
							</div>
							<div class="4u 12u(mobile)">
								<article class="box style2">
								<!--		<a id="leanModal" href="#job3" class="image featured"><img src="images/huflit.jpg" alt="" /></a> -->
									<h3><a id="leanModal" href="#">UNIVERSITY CAMPING TRIP – “HUFLIT’S 36 HOURS of LOVE”</a></h3>

								</article>
							</div>
						</div>

						<div id="job1" class="article">
							<p>Active member participating in “Thuy’s Dream” program, which was initiated by a major national newspaper, to provide material and spiritual support to children with cancer.</p>
						</div>

						<div id="job2" class="article">
							<p>Organizer of a social photo display to raise funds from local corporations for dioxin-poisoned victims in 2010. </p>
						</div>

						<div id="job3" class="article">
							<p>Key organizer of the University 2-day camping trip for more than a hundred students to a beach city 200km away from Ho Chi Minh City.</p>
						</div>

					</div>
					<footer>
						<p>Having a good impression?</p>
						<a href="#contact" class="button big scrolly">Get in touch with me</a>
					</footer>
				</article>
			</div>

		<!-- Contact -->
			<div class="wrapper style4">
				<article id="contact" class="container 75%">

					<div>
				
						<div class="row">
							<div class="12u">

								<header>
									<h2>Have me make stuff for you.</h2>
									<p>"We are what we repeatedly do. Excellence then, is not an act, but a habit." – Aristotle</p>
								</header>
								<h3>Find me on ...</h3>
								<ul class="social">
									<li><a target="_blank" href="https://www.facebook.com/doanduy.vy" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
									<li><a href="https://vn.linkedin.com/pub/vy-doan/82/4a2/682" class="icon fa-linkedin"><span class="label">LinkedIn</span></a></li>
									<li><a href="skype:vy.esl?chat" class="icon fa-skype"><span class="label">Skype</span></a></li>
									<li><a href="mailto:doanduy.vy@gmail.com" class="icon fa-envelope"><span class="label">Skype</span></a></li>
									<li><a href="tel:+84949826170" class="icon fa-phone" alt="+84949826170"><span class="label">Phone</span></a></li>
								</ul>
								<hr />
							</div>
						</div>
					</div>
					<footer>
						<ul id="copyright">
							<li>&copy; All rights reserved.</li><li>Created by: <a href="https://tuannvm.com">Tuan Nguyen</a></li>
						</ul>
					</footer>
				</article>
			</div>

		<!-- Scripts -->
			<script src="js/jquery.min.js"></script>
			<script src="js/jquery.scrolly.min.js"></script>
			<script src="js/skel.min.js"></script>
			<script src="js/skel-viewport.min.js"></script>
			<script src="js/util.js"></script>
			<!--[if lte IE 8]><script src="js/ie/respond.min.js"></script><![endif]-->
			<script src="js/main.js"></script>
			<script type="text/javascript" src="js/jquery.leanModal.min.js"></script>
			<script src="js/dialog.js"></script>

	</body>
</html>
